apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: ecommerce
spec:
  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those
  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.
  consolidation:
    enabled: true
  # Requirements that constrain the parameters of provisioned nodes.
  # These requirements are combined with pod.spec.affinity.nodeAffinity rules.
  # Operators { In, NotIn } are supported to enable including or excluding values
  requirements:
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
  # Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-cluster-name
    subnetSelector:
      karpenter.sh/discovery: 'cluster-name'
    securityGroupSelector:
      karpenter.sh/discovery/cluster-name: 'cluster-name'
  labels:
    managedBy: karpenter
    billing-team: ecommerce